### ISSUE TITLE
gnome-shell-3.26.2-r2

### ISSUE THREAD

**Issue by MikeyG** [hhfeuer/Gentoo-Gnome-3.26-X#5]
I was trying to emerge gnome-shell-3.26.2-r2:
```
[ebuild     U ~] gnome-base/gnome-shell-3.26.2-r2::gnome [3.26.2-r1::Gnome-3-26-X] USE="browser-extension ibus networkmanager nsplugin -bluetooth (-openrc-force) -test%" PYTHON_TARGETS="python3_4 python3_6 -python3_5" 0 KiB
```
I get the error:

meson.build:98:2: ERROR:  Native dependency 'gnome-bluetooth-1.0' not found

It does not seem to honor the -bluetooth flag.

**Comment by hhfeuer** [comment]
Yes, bluetooth is not optional with vanilla gnome-shell, it requires patching to honor USE="-bluetooth". This overlay contains patches for the most commonly used use flags, but not that one. I'll see if this can be easily done.

**Comment by MikeyG** [comment]
That's no problem, I'll just add in the bluetooth which really will not upset things.

**Comment by MikeyG** [comment]
I added the required bluetooth packages and everything worked.
